version: 2

sources:
    - name: staging
      database: neon-runway-359404
      schema: dbtProjID

      tables:
        - name: yellow_tripdata

models:
    - name: 1st_dbt_table
      description: >
        writing my first model for CI testing
      columns:
        - name: tripid
          description: Testing for uniqueness
          tests: 
            - unique:
                severity: warn
            - not_null:
                severity: warn